apiVersion: v1
kind: ConfigMap
metadata:
  name: db-secret-credentials
  namespace: go-k8s-demo
  labels:
    app: postgres
data:
  POSTGRES_DB: "go-demo-with-k8s"
  POSTGRES_USER: "postgres"
  POSTGRES_PASSWORD: "postgres"